### PR TITLE
Updated links, Second Class Added, Reveal Accessibility Plugin

### PR DESCRIPTION
**Pull request by marcysutton**
I've had a fork of these slides for a while now, so I figured it was time to submit a pull request! I've taught the class two times for Girl Develop It Seattle. Here are some features in the slides:

* Accessibility plugin: really hides inactive slide content, dynamically generates skip links for slides
* Updated links and content in Class 1
* New Class 2: HTML and CSS accessibility, hands-on exercises 

Let me know if I need to host images instead of including them. Thanks!

### CODE REVIEW

**Comment by Roenok** [comment]
Love some of the stuff you have added! The class 2 slides are very sparse; do you have plans to build out some of the content?

**Comment by marcysutton** [comment]
I wasn't planning on it. It could be that my presentation style is different than the original...I tend to create more info-dense slides to use as a reference. I could have left out important details on accident though...things like what I use the Web Developer toolbar for (added to the Headings section). After teaching the whole thing twice, it seemed like a good amount of content.

**Comment by Roenok** [comment]
Okay, I see more content in your branch. Let me double-check to make sure that it is not just a me-merging-wrong issue.

**Comment by marcysutton** [comment]
Ahh. Here is a link to the compiled slides: http://marcysutton.github.io/gdi-web-accessibility/

We can certainly make changes to them, I'm not against it! I just don't have as much time to work on them as I'd like. :)

**Comment by Roenok** [comment]
Yeah, when I tried to merge them I got an intermediate version of the slides with only headers and no content. This is much nicer!

Let's see if I can clear the merge conflicts quickly.

**Comment by marcysutton** [comment]
I tried to get fancy by squashing some commits, which may not have helped. Let me know if you want to pair!

**Comment by Roenok** [comment]
I've got a GDI class tonight where some of our instructors and TAs are GitHub guros. I'm going to attempt the merge with them there to help. I'll let you know how it goes!

**Comment by marcysutton** [comment]
Ok great! Please let me know if merging continues to suck, I can just resubmit the PR without squashed commits. Sorry for the trouble!

**Comment by marcysutton** [comment]
Hi @Roenok, I have rebased the PR to resolve conflicts. The commits are no longer squashed, revealing a pretty noisy commit history. Let me know if you would like it cleaned up, otherwise this should be good to go!

**Comment by Roenok** [comment]
Very lovely, thanks! I'll go ahead and merge these.

**Comment by marcysutton** [comment]
Yay! :tada: Thanks @Roenok!

**Pull request merged**
